// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/database/models/agent_message.dart';
import 'core/database/models/agent_session.dart';
import 'core/database/models/isar_chunk.dart';
import 'core/database/models/isar_document.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7393362435309882679),
    name: 'IsarChunk',
    lastPropertyId: const obx_int.IdUid(4, 5820799283109081396),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8055524599437241377),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3229320536858231276),
        name: 'docId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 5945145856801249738),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9173768353573935062),
        name: 'chunkText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5820799283109081396),
        name: 'chunkVector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 7534749869295989484),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1536),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 300154422845590284),
    name: 'IsarDocument',
    lastPropertyId: const obx_int.IdUid(4, 3857920786029271033),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 671837981270546382),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5006569386958696108),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8277877743548274701),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3857920786029271033),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4628304068115018924),
    name: 'AgentMessage',
    lastPropertyId: const obx_int.IdUid(5, 454225009785019217),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7178741696237399183),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5152858179064754666),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4713148633818875281),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2921825090262286210),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 454225009785019217),
        name: 'sessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4861661707765533784),
        relationField: 'session',
        relationTarget: 'AgentSession',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8404905154945929728),
    name: 'AgentSession',
    lastPropertyId: const obx_int.IdUid(7, 193308306984325435),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1661193524083871441),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6595368305023697912),
        name: 'agentType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5036546111768919035),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1277739398577420041),
        name: 'relatedDocId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3846771886876106909),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5691253640660306288),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 193308306984325435),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'AgentMessage',
        srcField: 'session',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8404905154945929728),
    lastIndexId: const obx_int.IdUid(3, 4861661707765533784),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    IsarChunk: obx_int.EntityDefinition<IsarChunk>(
      model: _entities[0],
      toOneRelations: (IsarChunk object) => [],
      toManyRelations: (IsarChunk object) => {},
      getId: (IsarChunk object) => object.id,
      setId: (IsarChunk object, int id) {
        object.id = id;
      },
      objectToFB: (IsarChunk object, fb.Builder fbb) {
        final chunkTextOffset = fbb.writeString(object.chunkText);
        final chunkVectorOffset = object.chunkVector == null
            ? null
            : fbb.writeListFloat32(object.chunkVector!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.docId);
        fbb.addOffset(2, chunkTextOffset);
        fbb.addOffset(3, chunkVectorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final docIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final chunkTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final chunkVectorParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = IsarChunk(
          id: idParam,
          docId: docIdParam,
          chunkText: chunkTextParam,
          chunkVector: chunkVectorParam,
        );

        return object;
      },
    ),
    IsarDocument: obx_int.EntityDefinition<IsarDocument>(
      model: _entities[1],
      toOneRelations: (IsarDocument object) => [],
      toManyRelations: (IsarDocument object) => {},
      getId: (IsarDocument object) => object.id,
      setId: (IsarDocument object, int id) {
        object.id = id;
      },
      objectToFB: (IsarDocument object, fb.Builder fbb) {
        final fileNameOffset = fbb.writeString(object.fileName);
        final filePathOffset = fbb.writeString(object.filePath);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, fileNameOffset);
        fbb.addOffset(2, filePathOffset);
        fbb.addInt64(3, object.createdAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final object = IsarDocument(
          id: idParam,
          fileName: fileNameParam,
          filePath: filePathParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    AgentMessage: obx_int.EntityDefinition<AgentMessage>(
      model: _entities[2],
      toOneRelations: (AgentMessage object) => [object.session],
      toManyRelations: (AgentMessage object) => {},
      getId: (AgentMessage object) => object.id,
      setId: (AgentMessage object, int id) {
        object.id = id;
      },
      objectToFB: (AgentMessage object, fb.Builder fbb) {
        final roleOffset = fbb.writeString(object.role);
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, roleOffset);
        fbb.addOffset(2, textOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.session.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = AgentMessage(
          id: idParam,
          role: roleParam,
          text: textParam,
          createdAt: createdAtParam,
        );
        object.session.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.session.attach(store);
        return object;
      },
    ),
    AgentSession: obx_int.EntityDefinition<AgentSession>(
      model: _entities[3],
      toOneRelations: (AgentSession object) => [],
      toManyRelations: (AgentSession object) => {
        obx_int.RelInfo<AgentMessage>.toOneBacklink(
          5,
          object.id,
          (AgentMessage srcObject) => srcObject.session,
        ): object.messages,
      },
      getId: (AgentSession object) => object.id,
      setId: (AgentSession object, int id) {
        object.id = id;
      },
      objectToFB: (AgentSession object, fb.Builder fbb) {
        final agentTypeOffset = fbb.writeString(object.agentType);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, agentTypeOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.relatedDocId);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(6, object.isPinned);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final agentTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final relatedDocIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = AgentSession(
          id: idParam,
          agentType: agentTypeParam,
          title: titleParam,
          relatedDocId: relatedDocIdParam,
          isPinned: isPinnedParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<AgentSession>(
          object.messages,
          store,
          obx_int.RelInfo<AgentMessage>.toOneBacklink(
            5,
            object.id,
            (AgentMessage srcObject) => srcObject.session,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [IsarChunk] entity fields to define ObjectBox queries.
class IsarChunk_ {
  /// See [IsarChunk.id].
  static final id = obx.QueryIntegerProperty<IsarChunk>(
    _entities[0].properties[0],
  );

  /// See [IsarChunk.docId].
  static final docId = obx.QueryIntegerProperty<IsarChunk>(
    _entities[0].properties[1],
  );

  /// See [IsarChunk.chunkText].
  static final chunkText = obx.QueryStringProperty<IsarChunk>(
    _entities[0].properties[2],
  );

  /// See [IsarChunk.chunkVector].
  static final chunkVector = obx.QueryHnswProperty<IsarChunk>(
    _entities[0].properties[3],
  );
}

/// [IsarDocument] entity fields to define ObjectBox queries.
class IsarDocument_ {
  /// See [IsarDocument.id].
  static final id = obx.QueryIntegerProperty<IsarDocument>(
    _entities[1].properties[0],
  );

  /// See [IsarDocument.fileName].
  static final fileName = obx.QueryStringProperty<IsarDocument>(
    _entities[1].properties[1],
  );

  /// See [IsarDocument.filePath].
  static final filePath = obx.QueryStringProperty<IsarDocument>(
    _entities[1].properties[2],
  );

  /// See [IsarDocument.createdAt].
  static final createdAt = obx.QueryDateProperty<IsarDocument>(
    _entities[1].properties[3],
  );
}

/// [AgentMessage] entity fields to define ObjectBox queries.
class AgentMessage_ {
  /// See [AgentMessage.id].
  static final id = obx.QueryIntegerProperty<AgentMessage>(
    _entities[2].properties[0],
  );

  /// See [AgentMessage.role].
  static final role = obx.QueryStringProperty<AgentMessage>(
    _entities[2].properties[1],
  );

  /// See [AgentMessage.text].
  static final text = obx.QueryStringProperty<AgentMessage>(
    _entities[2].properties[2],
  );

  /// See [AgentMessage.createdAt].
  static final createdAt = obx.QueryDateProperty<AgentMessage>(
    _entities[2].properties[3],
  );

  /// See [AgentMessage.session].
  static final session = obx.QueryRelationToOne<AgentMessage, AgentSession>(
    _entities[2].properties[4],
  );
}

/// [AgentSession] entity fields to define ObjectBox queries.
class AgentSession_ {
  /// See [AgentSession.id].
  static final id = obx.QueryIntegerProperty<AgentSession>(
    _entities[3].properties[0],
  );

  /// See [AgentSession.agentType].
  static final agentType = obx.QueryStringProperty<AgentSession>(
    _entities[3].properties[1],
  );

  /// See [AgentSession.title].
  static final title = obx.QueryStringProperty<AgentSession>(
    _entities[3].properties[2],
  );

  /// See [AgentSession.relatedDocId].
  static final relatedDocId = obx.QueryIntegerProperty<AgentSession>(
    _entities[3].properties[3],
  );

  /// See [AgentSession.createdAt].
  static final createdAt = obx.QueryDateProperty<AgentSession>(
    _entities[3].properties[4],
  );

  /// See [AgentSession.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AgentSession>(
    _entities[3].properties[5],
  );

  /// See [AgentSession.isPinned].
  static final isPinned = obx.QueryBooleanProperty<AgentSession>(
    _entities[3].properties[6],
  );

  /// see [AgentSession.messages]
  static final messages = obx.QueryBacklinkToMany<AgentMessage, AgentSession>(
    AgentMessage_.session,
  );
}
